version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: showcase_db
    environment:
      POSTGRES_USER: dev_useripy
      POSTGRES_PASSWORD: dev_passwordipy
      POSTGRES_DB: iplanify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
